### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by igitur** [jnm2/LowLevelHooking#1]
Please provide an example of how to use this.

**Comment by jnm2** [comment]
@igitur Will do, I'll add a readme with code snippets and a sample project.

**Comment by jnm2** [comment]
I added a sample application. Next I'll write a readme.

If you'd like to play with it before I'm finished with the documentation work, you can find it here: https://github.com/jnm2/LowLevelHooking/tree/documentation/src/Samples/WinForms

**Comment by jnm2** [comment]
@igitur See https://github.com/jnm2/LowLevelHooking#get-up-and-running and https://github.com/jnm2/LowLevelHooking/tree/master/src/Samples.
