### ISSUE TITLE
Apply to Windows Service app

### ISSUE THREAD

**Issue by quyenbc** [jnm2/LowLevelHooking#2]
Hi friend, I want to apply your library to write a small application in the form of Windows service to listen to barcode reader. Could you please suggest how I can implement this library for windows service app?

**Comment by jnm2** [comment]
Oops, sorry I missed this question! I'm not overly familiar with your question, but I believe Windows services are executed on a non-interactive desktop that never has access to keyboard or mouse input.  My guess is that you'd need the service to start a non-service tray application or something like that and use inter-process communication.
